import React, { useState, useEffect } from 'react';
import { 
  Plug, 
  Settings, 
  CheckCircle, 
  AlertCircle, 
  Clock, 
  Plus, 
  Search, 
  Filter, 
  Download, 
  Upload, 
  RefreshCw, 
  ExternalLink, 
  Shield, 
  Key, 
  Database, 
  Cloud, 
  Smartphone, 
  Globe, 
  Mail, 
  MessageSquare, 
  Calendar, 
  CreditCard, 
  BarChart3, 
  Users, 
  FileText, 
  Image, 
  Video, 
  Music, 
  Code, 
  Zap, 
  Link, 
  Layers, 
  Network, 
  Server, 
  HardDrive, 
  Wifi, 
  Bluetooth, 
  Radio, 
  Tv, 
  Monitor, 
  Tablet, 
  Watch, 
  Headphones, 
  Camera, 
  Mic, 
  Speaker, 
  Gamepad2, 
  Joystick, 
  Cpu, 
  MemoryStick, 
  SdCard, 
  Usb, 
  Printer, 
  Scanner, 
  Fax, 
  Phone, 
  PhoneCall, 
  Voicemail, 
  MessageCircle, 
  Send, 
  Inbox, 
  Archive, 
  Trash2, 
  Star, 
  Heart, 
  ThumbsUp, 
  ThumbsDown, 
  Share2, 
  Bookmark, 
  Flag, 
  Tag, 
  Hash, 
  AtSign, 
  DollarSign, 
  Percent, 
  Euro, 
  PoundSterling, 
  Yen, 
  Bitcoin, 
  CreditCard as CreditCardIcon, 
  Banknote, 
  Wallet, 
  ShoppingCart, 
  ShoppingBag, 
  Package, 
  Truck, 
  Plane, 
  Ship, 
  Train, 
  Car, 
  Bike, 
  Bus, 
  Taxi, 
  MapPin, 
  Map, 
  Navigation, 
  Compass, 
  Route, 
  Milestone, 
  Flag as FlagIcon, 
  Home, 
  Building, 
  Building2, 
  Store, 
  Warehouse, 
  Factory, 
  Hospital, 
  School, 
  University, 
  GraduationCap, 
  BookOpen, 
  Book, 
  Newspaper, 
  FileText as FileTextIcon, 
  File, 
  Folder, 
  FolderOpen, 
  Archive as ArchiveIcon, 
  Paperclip, 
  Scissors, 
  Copy, 
  Clipboard, 
  Edit, 
  Edit2, 
  Edit3, 
  PenTool, 
  Highlighter, 
  Type, 
  Bold, 
  Italic, 
  Underline, 
  AlignLeft, 
  AlignCenter, 
  AlignRight, 
  AlignJustify, 
  List, 
  ListOrdered, 
  Indent, 
  Outdent, 
  Quote, 
  Code2, 
  Terminal, 
  Command, 
  Option, 
  Alt, 
  Shift, 
  Ctrl, 
  Space, 
  Enter, 
  Backspace, 
  Delete, 
  Tab, 
  CapsLock, 
  Escape, 
  Function, 
  ArrowUp, 
  ArrowDown, 
  ArrowLeft, 
  ArrowRight, 
  ChevronUp, 
  ChevronDown, 
  ChevronLeft, 
  ChevronRight, 
  ChevronsUp, 
  ChevronsDown, 
  ChevronsLeft, 
  ChevronsRight, 
  CornerUpLeft, 
  CornerUpRight, 
  CornerDownLeft, 
  CornerDownRight, 
  Move, 
  MousePointer, 
  MousePointer2, 
  Hand, 
  Grab, 
  GrabHand, 
  Pointer, 
  Click, 
  Touch, 
  Fingerprint, 
  Eye, 
  EyeOff, 
  Glasses, 
  SunMedium, 
  Moon, 
  CloudSun, 
  CloudRain, 
  CloudSnow, 
  CloudLightning, 
  Umbrella, 
  Thermometer, 
  Wind, 
  Tornado, 
  Waves, 
  Droplets, 
  Snowflake, 
  Sun, 
  Sunrise, 
  Sunset, 
  Eclipse, 
  Cloudy, 
  PartlyCloudy, 
  Overcast, 
  Drizzle, 
  Rain, 
  Snow, 
  Sleet, 
  Hail, 
  Thunder, 
  Lightning, 
  Fog, 
  Mist, 
  Haze, 
  Dust, 
  Smoke, 
  Fire, 
  Flame, 
  Candle, 
  Lightbulb, 
  Flashlight, 
  Lamp, 
  Lantern, 
  Torch, 
  Spotlight, 
  Laser, 
  Beam, 
  Rainbow, 
  Prism, 
  Crystal, 
  Diamond, 
  Gem, 
  Ring, 
  Crown, 
  Trophy, 
  Medal, 
  Award, 
  Ribbon, 
  Rosette, 
  Badge, 
  Certificate, 
  Diploma, 
  Scroll, 
  Document, 
  Contract, 
  Invoice, 
  Receipt, 
  Ticket, 
  Coupon, 
  Voucher, 
  Gift, 
  Present, 
  Balloon, 
  Party, 
  Cake, 
  Candles, 
  Confetti, 
  Fireworks, 
  Sparkles, 
  Sparkler, 
  Wand, 
  Magic, 
  Crystal as CrystalIcon, 
  Potion, 
  Elixir, 
  Bottle, 
  Flask, 
  TestTube, 
  Beaker, 
  Microscope, 
  Telescope, 
  Binoculars, 
  Magnifier, 
  MagnifyingGlass, 
  Lens, 
  Focus, 
  Zoom, 
  ZoomIn, 
  ZoomOut, 
  Maximize, 
  Minimize, 
  Maximize2, 
  Minimize2, 
  Expand, 
  Shrink, 
  Fullscreen, 
  ExitFullscreen, 
  PictureInPicture, 
  PictureInPicture2, 
  Sidebar, 
  PanelLeft, 
  PanelRight, 
  PanelTop, 
  PanelBottom, 
  Layout, 
  LayoutGrid, 
  LayoutList, 
  LayoutTemplate, 
  Columns, 
  Rows, 
  Grid, 
  Table, 
  TableProperties, 
  Spreadsheet, 
  Calculator, 
  Abacus, 
  Ruler, 
  Triangle, 
  Square, 
  Circle, 
  Pentagon, 
  Hexagon, 
  Octagon, 
  Star as StarIcon, 
  Heart as HeartIcon, 
  Spade, 
  Club, 
  Diamond as DiamondIcon, 
  Dice1, 
  Dice2, 
  Dice3, 
  Dice4, 
  Dice5, 
  Dice6, 
  Puzzle, 
  PuzzlePiece, 
  Jigsaw, 
  Blocks, 
  Brick, 
  Wall, 
  Fence, 
  Gate, 
  Door, 
  DoorOpen, 
  DoorClosed, 
  Window, 
  Blinds, 
  Curtains, 
  Bed, 
  Pillow, 
  Blanket, 
  Sofa, 
  Chair, 
  Desk, 
  Table as TableIcon, 
  Lamp as LampIcon, 
  Clock as ClockIcon, 
  Alarm, 
  Timer, 
  Stopwatch, 
  Hourglass, 
  Calendar as CalendarIcon, 
  CalendarDays, 
  CalendarCheck, 
  CalendarX, 
  CalendarPlus, 
  CalendarMinus, 
  CalendarClock, 
  CalendarHeart, 
  CalendarRange, 
  Date, 
  Time, 
  Schedule, 
  Agenda, 
  Appointment, 
  Meeting, 
  Conference, 
  Presentation, 
  Projector, 
  Screen, 
  Whiteboard, 
  Blackboard, 
  Chalkboard, 
  Easel, 
  Canvas, 
  Palette, 
  Brush, 
  Paintbrush, 
  Pencil, 
  Pen, 
  Marker, 
  Crayon, 
  Eraser, 
  Sharpener, 
  Stapler, 
  PaperClip, 
  Pushpin, 
  Thumbtack, 
  Pin, 
  Needle, 
  Thread, 
  Scissors as ScissorsIcon, 
  Knife, 
  Fork, 
  Spoon, 
  Plate, 
  Bowl, 
  Cup, 
  Mug, 
  Glass, 
  Bottle as BottleIcon, 
  Can, 
  Jar, 
  Box, 
  Container, 
  Basket, 
  Bag, 
  Suitcase, 
  Backpack, 
  Briefcase, 
  Handbag, 
  Purse, 
  Wallet as WalletIcon, 
  Pocket, 
  Zipper, 
  Button, 
  Buckle, 
  Belt, 
  Tie, 
  Bowtie, 
  Scarf, 
  Hat, 
  Cap, 
  Helmet, 
  Mask, 
  Sunglasses, 
  Glasses as GlassesIcon, 
  Monocle, 
  Eyepatch, 
  Bandage, 
  Plaster, 
  Pill, 
  Capsule, 
  Syringe, 
  Stethoscope, 
  Thermometer as ThermometerIcon, 
  Bandaid, 
  FirstAid, 
  Medical, 
  Health, 
  Fitness, 
  Dumbbell, 
  Barbell, 
  Weight, 
  Scale, 
  Treadmill, 
  Bike as BikeIcon, 
  Swim, 
  Run, 
  Walk, 
  Yoga, 
  Meditation, 
  Zen, 
  Peace, 
  Love, 
  Hug, 
  Kiss, 
  Smile, 
  Laugh, 
  Cry, 
  Sad, 
  Angry, 
  Mad, 
  Surprised, 
  Shocked, 
  Confused, 
  Worried, 
  Scared, 
  Happy, 
  Joy, 
  Excited, 
  Calm, 
  Relaxed, 
  Sleepy, 
  Tired, 
  Energetic, 
  Strong, 
  Weak, 
  Sick, 
  Healthy, 
  Hot, 
  Cold, 
  Warm, 
  Cool, 
  Dry, 
  Wet, 
  Clean, 
  Dirty, 
  Fresh, 
  Stale, 
  New, 
  Old, 
  Young, 
  Adult, 
  Child, 
  Baby, 
  Family, 
  Parents, 
  Mother, 
  Father, 
  Sister, 
  Brother, 
  Grandmother, 
  Grandfather, 
  Aunt, 
  Uncle, 
  Cousin, 
  Friend, 
  Stranger, 
  Neighbor, 
  Colleague, 
  Boss, 
  Employee, 
  Student, 
  Teacher, 
  Doctor, 
  Nurse, 
  Lawyer, 
  Judge, 
  Police, 
  Firefighter, 
  Soldier, 
  Pilot, 
  Driver, 
  Chef, 
  Waiter, 
  Cashier, 
  Salesperson, 
  Manager, 
  Director, 
  CEO, 
  President, 
  King, 
  Queen, 
  Prince, 
  Princess, 
  Knight, 
  Wizard, 
  Witch, 
  Angel, 
  Devil, 
  Ghost, 
  Monster, 
  Alien, 
  Robot, 
  Cyborg, 
  Android, 
  AI, 
  Computer, 
  Laptop, 
  Desktop, 
  Server as ServerIcon, 
  Mainframe, 
  Supercomputer, 
  Quantum, 
  Processor, 
  Chip, 
  Circuit, 
  Board, 
  Wire, 
  Cable, 
  Connector, 
  Port, 
  Socket, 
  Plug as PlugIcon, 
  Adapter, 
  Converter, 
  Transformer, 
  Generator, 
  Battery, 
  Charger, 
  Power, 
  Energy, 
  Electricity, 
  Voltage, 
  Current, 
  Resistance, 
  Capacitor, 
  Inductor, 
  Resistor, 
  Transistor, 
  Diode, 
  LED, 
  Laser as LaserIcon, 
  Fiber, 
  Optic, 
  Light, 
  Photon, 
  Electron, 
  Proton, 
  Neutron, 
  Atom, 
  Molecule, 
  Element, 
  Compound, 
  Chemical, 
  Formula, 
  Equation, 
  Math, 
  Number, 
  Digit, 
  Zero, 
  One, 
  Two, 
  Three, 
  Four, 
  Five, 
  Six, 
  Seven, 
  Eight, 
  Nine, 
  Ten, 
  Hundred, 
  Thousand, 
  Million, 
  Billion, 
  Trillion, 
  Infinity, 
  Pi, 
  E, 
  Phi, 
  Alpha, 
  Beta, 
  Gamma, 
  Delta, 
  Epsilon, 
  Zeta, 
  Eta, 
  Theta, 
  Iota, 
  Kappa, 
  Lambda, 
  Mu, 
  Nu, 
  Xi, 
  Omicron, 
  Pi as PiIcon, 
  Rho, 
  Sigma, 
  Tau, 
  Upsilon, 
  Phi as PhiIcon, 
  Chi, 
  Psi, 
  Omega, 
  A, 
  B, 
  C, 
  D, 
  E as EIcon, 
  F, 
  G, 
  H, 
  I, 
  J, 
  K, 
  L, 
  M, 
  N, 
  O, 
  P, 
  Q, 
  R, 
  S, 
  T, 
  U, 
  V, 
  W, 
  X, 
  Y, 
  Z
} from 'lucide-react';

const ThirdPartyIntegrationHub = () => {
  const [activeTab, setActiveTab] = useState('overview');
  const [selectedCategory, setSelectedCategory] = useState('all');
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedIntegration, setSelectedIntegration] = useState(null);
  const [showConnectModal, setShowConnectModal] = useState(false);
  const [integrations, setIntegrations] = useState([]);
  const [connectedIntegrations, setConnectedIntegrations] = useState([]);
  const [isLoading, setIsLoading] = useState(false);

  // Integration categories
  const categories = [
    { id: 'all', name: 'All Integrations', icon: Globe, count: 0 },
    { id: 'communication', name: 'Communication', icon: MessageSquare, count: 0 },
    { id: 'social', name: 'Social Media', icon: Users, count: 0 },
    { id: 'productivity', name: 'Productivity', icon: FileText, count: 0 },
    { id: 'analytics', name: 'Analytics', icon: BarChart3, count: 0 },
    { id: 'payment', name: 'Payment', icon: CreditCard, count: 0 },
    { id: 'storage', name: 'Storage', icon: Database, count: 0 },
    { id: 'calendar', name: 'Calendar', icon: Calendar, count: 0 },
    { id: 'crm', name: 'CRM', icon: Users, count: 0 },
    { id: 'marketing', name: 'Marketing', icon: Zap, count: 0 }
  ];

  // Available integrations
  useEffect(() => {
    const sampleIntegrations = [
      // Communication
      {
        id: 1,
        name: 'Slack',
        description: 'Team communication and collaboration platform',
        category: 'communication',
        icon: MessageSquare,
        status: 'available',
        popularity: 95,
        rating: 4.8,
        users: '12M+',
        features: [
          'Real-time messaging',
          'File sharing',
          'Video calls',
          'Channel organization',
          'Bot integrations'
        ],
        benefits: [
          'Improved team communication',
          'Centralized notifications',
          'Automated relationship updates',
          'Team collaboration on relationship goals'
        ],
        setupTime: '5 minutes',
        difficulty: 'Easy',
        pricing: 'Free tier available',
        documentation: 'https://api.slack.com/docs',
        webhookSupport: true,
        apiVersion: 'v1.7',
        lastUpdated: '2025-01-06'
      },
      {
        id: 2,
        name: 'Discord',
        description: 'Voice, video, and text communication for communities',
        category: 'communication',
        icon: MessageCircle,
        status: 'available',
        popularity: 88,
        rating: 4.6,
        users: '150M+',
        features: [
          'Voice channels',
          'Text messaging',
          'Screen sharing',
          'Server organization',
          'Bot ecosystem'
        ],
        benefits: [
          'Community building',
          'Voice communication',
          'Event coordination',
          'Group relationship activities'
        ],
        setupTime: '10 minutes',
        difficulty: 'Medium',
        pricing: 'Free with premium options',
        documentation: 'https://discord.com/developers/docs',
        webhookSupport: true,
        apiVersion: 'v10',
        lastUpdated: '2025-01-05'
      },
      // Social Media
      {
        id: 3,
        name: 'Facebook',
        description: 'Social networking and relationship sharing platform',
        category: 'social',
        icon: Users,
        status: 'connected',
        popularity: 98,
        rating: 4.2,
        users: '2.9B+',
        features: [
          'Profile integration',
          'Relationship status updates',
          'Photo sharing',
          'Event creation',
          'Friend connections'
        ],
        benefits: [
          'Social relationship validation',
          'Milestone sharing',
          'Event planning',
          'Friend network insights'
        ],
        setupTime: '3 minutes',
        difficulty: 'Easy',
        pricing: 'Free',
        documentation: 'https://developers.facebook.com/docs',
        webhookSupport: true,
        apiVersion: 'v18.0',
        lastUpdated: '2025-01-07'
      },
      {
        id: 4,
        name: 'Instagram',
        description: 'Photo and video sharing social platform',
        category: 'social',
        icon: Image,
        status: 'available',
        popularity: 92,
        rating: 4.5,
        users: '2B+',
        features: [
          'Photo sharing',
          'Story integration',
          'Reels creation',
          'Direct messaging',
          'Hashtag tracking'
        ],
        benefits: [
          'Visual relationship documentation',
          'Milestone celebrations',
          'Memory sharing',
          'Social engagement'
        ],
        setupTime: '5 minutes',
        difficulty: 'Easy',
        pricing: 'Free',
        documentation: 'https://developers.facebook.com/docs/instagram-api',
        webhookSupport: true,
        apiVersion: 'v18.0',
        lastUpdated: '2025-01-06'
      },
      // Productivity
      {
        id: 5,
        name: 'Google Workspace',
        description: 'Productivity suite with docs, sheets, and calendar',
        category: 'productivity',
        icon: FileText,
        status: 'connected',
        popularity: 89,
        rating: 4.7,
        users: '3B+',
        features: [
          'Document collaboration',
          'Spreadsheet integration',
          'Calendar sync',
          'Drive storage',
          'Gmail integration'
        ],
        benefits: [
          'Shared relationship planning',
          'Goal tracking spreadsheets',
          'Calendar coordination',
          'Document sharing'
        ],
        setupTime: '8 minutes',
        difficulty: 'Medium',
        pricing: 'Free tier available',
        documentation: 'https://developers.google.com/workspace',
        webhookSupport: true,
        apiVersion: 'v1',
        lastUpdated: '2025-01-07'
      },
      {
        id: 6,
        name: 'Microsoft 365',
        description: 'Office productivity suite and collaboration tools',
        category: 'productivity',
        icon: FileText,
        status: 'available',
        popularity: 85,
        rating: 4.4,
        users: '345M+',
        features: [
          'Office applications',
          'Teams integration',
          'OneDrive storage',
          'Outlook calendar',
          'SharePoint collaboration'
        ],
        benefits: [
          'Professional planning tools',
          'Team collaboration',
          'Document management',
          'Calendar integration'
        ],
        setupTime: '12 minutes',
        difficulty: 'Medium',
        pricing: 'Subscription required',
        documentation: 'https://docs.microsoft.com/en-us/graph/',
        webhookSupport: true,
        apiVersion: 'v1.0',
        lastUpdated: '2025-01-05'
      },
      // Analytics
      {
        id: 7,
        name: 'Google Analytics',
        description: 'Web analytics and user behavior tracking',
        category: 'analytics',
        icon: BarChart3,
        status: 'available',
        popularity: 94,
        rating: 4.6,
        users: '56M+',
        features: [
          'User behavior tracking',
          'Conversion analysis',
          'Custom events',
          'Real-time data',
          'Advanced reporting'
        ],
        benefits: [
          'Relationship app usage insights',
          'User engagement tracking',
          'Feature adoption analysis',
          'Performance optimization'
        ],
        setupTime: '15 minutes',
        difficulty: 'Hard',
        pricing: 'Free tier available',
        documentation: 'https://developers.google.com/analytics',
        webhookSupport: false,
        apiVersion: 'v4',
        lastUpdated: '2025-01-04'
      },
      {
        id: 8,
        name: 'Mixpanel',
        description: 'Advanced product analytics and user tracking',
        category: 'analytics',
        icon: BarChart3,
        status: 'available',
        popularity: 78,
        rating: 4.5,
        users: '26K+',
        features: [
          'Event tracking',
          'Funnel analysis',
          'Cohort analysis',
          'A/B testing',
          'User segmentation'
        ],
        benefits: [
          'Deep user behavior insights',
          'Relationship journey analysis',
          'Feature

